spring:
  application:
    name: Appointement
  config:
    import: optional:configserver:http://localhost:8888

  mail:
    host: smtp.gmail.com
    port: 587
    username: houssemjallouli99@gmail.com
    password: uujtoekvvvctgxsq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true